/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testlog4cpp_MainActivity */

#ifndef _Included_com_example_testlog4cpp_MainActivity
#define _Included_com_example_testlog4cpp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testlog4cpp_MainActivity
 * Method:    testNativeLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testlog4cpp_MainActivity_testNativeLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
